name: ebook
description: "PDF doc viewer"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.6
  octo_image: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/preview/1/
    - assets/images/preview/2/
    - assets/images/preview/3/
    - assets/images/preview/4/
    - assets/images/preview/5/
    - assets/images/preview/6/
    - assets/images/preview/7/
    - assets/images/preview/8/
    - assets/images/preview/9/
    - assets/images/preview/10/
    - assets/images/preview/11/
    - assets/images/preview/12/
    - assets/images/preview/13/
    - assets/images/preview/14/
    - assets/images/preview/15/
    - assets/images/preview/16/
    - assets/images/preview/17/
    - assets/images/preview/18/
    - assets/images/full/1/
    - assets/images/full/2/
    - assets/images/full/3/
    - assets/images/full/4/
    - assets/images/full/5/
    - assets/images/full/6/
    - assets/images/full/7/
    - assets/images/full/8/
    - assets/images/full/9/
    - assets/images/full/10/
    - assets/images/full/11/
    - assets/images/full/12/
    - assets/images/full/13/
    - assets/images/full/14/
    - assets/images/full/15/
    - assets/images/full/16/
    - assets/images/full/17/
    - assets/images/full/18/